import { useState, type FormEvent } from 'react'
import { Navigate, useLocation, useNavigate } from 'react-router-dom'
import { useAuth } from '../auth/AuthProvider'

export function LoginPage() {
  const { user, login } = useAuth(); const navigate = useNavigate(); const location = useLocation()
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [rememberMe, setRememberMe] = useState(false); const [error, setError] = useState(''); const [busy, setBusy] = useState(false)
  if (user) return <Navigate to="/" replace />
  async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); setError(''); try { await login(email, password, rememberMe); const from = (location.state as { from?: { pathname?: string } } | null)?.from?.pathname; navigate(from ?? '/', { replace: true }) } catch (reason) { setError(reason instanceof Error ? reason.message : 'Login failed.') } finally { setBusy(false) } }
  return <div className="mx-auto max-w-md rounded-3xl border border-white/10 bg-white/5 p-8"><h1 className="text-3xl font-black">Welcome back</h1><p className="mt-2 text-slate-400">Accounts are created by an administrator.</p><form className="mt-7 space-y-5" onSubmit={submit}><label className="block text-sm">Email<input className="mt-2 w-full rounded-xl border border-white/15 bg-black/20 px-4 py-3 outline-none focus:border-emerald-400" type="email" autoComplete="email" required value={email} onChange={e => setEmail(e.target.value)} /></label><label className="block text-sm">Password<input className="mt-2 w-full rounded-xl border border-white/15 bg-black/20 px-4 py-3 outline-none focus:border-emerald-400" type="password" autoComplete="current-password" required value={password} onChange={e => setPassword(e.target.value)} /></label><label className="flex cursor-pointer items-center gap-3 text-sm text-slate-300"><input className="h-4 w-4 accent-emerald-400" type="checkbox" checked={rememberMe} onChange={event => setRememberMe(event.target.checked)} /><span><strong className="font-semibold text-white">Keep me logged in</strong><span className="mt-0.5 block text-xs text-slate-500">Stay signed in on this device for up to 30 days.</span></span></label>{error && <p className="text-sm text-rose-300">{error}</p>}<button disabled={busy} className="w-full rounded-xl bg-emerald-400 px-4 py-3 font-bold text-ink disabled:opacity-50">{busy ? 'Signing in…' : 'Sign in'}</button></form></div>
}
